미세먼지 프로젝트 완성본
codesquad-member-2020/dust-6 pull request #67
Opened 2020-04-04 12:41 UTC by reesekimm

미세먼지 프로젝트 마무리하여 PR 합니다.

- [WEB](http://34.236.160.204:80/) ─ 전 기능 구현 완료 ([기획서](https://docs.google.com/presentation/d/1Yl4nM2FReIhZASlBM73asWMcLe3366hglP8E_Dded1U/edit#slide=id.g7e682b64ec_0_9))
- [iOS](https://github.com/codesquad-member-2020/dust-6/blob/dev/iOS/dustDemo.gif)

> FE) 예보화면 애니메이션 구현 코드(`forecastView.js`)는 중복제거 등 리팩토링이 필요한 상태입니다.

2020-04-05 05:00 UTC, wheejuni requested changes
수고하셨습니다.
간단한 리뷰사항 남겨드렸으니 참고해주세요!

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/Dust6Application.java
> +@SpringBootApplication
앞으로는 BE/FE/iOS 별로 리뷰요청 따로 오픈해주시면 감사하겠습니다!

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/api/ApiDustStatusController.java
> +    public String location(CoordinateDTO coordinate) throws IOException, URISyntaxException {
`Controller` 에 request mapping 이외 목적의 `public` 메소드는 사용하지 말아주세요.

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/api/ApiForecastController.java
> +        for (int i = 1; i < 4; i++) {
모든 경우에 무조건 세 개만 딱 들어오는 건가요?

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/domain/MeasureDensityDTO.java
> +    @NotEmpty
bean validation 적용 좋습니다!!

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/domain/OverallDTO.java
> +    public OverallDTO(List<String> imageUrls, String informOverall, String informGrade) {
여긴 왜 lombok 사용 안했는지 이유 알 수 있을까요?

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/domain/ResponseDTO.java
> +    private Object data;
generic을 사용해보는 건 어땠을까요?

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/service/LocationService.java
> +public class LocationService {
이 클래스를 `@Service` 로 선언해주시고, 아래 static method들은 모두 static 키워드들을 제거해주세요.

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/service/LocationService.java
> +    public static List<DistanceDTO> distances(CoordinateDTO coordinate) throws URISyntaxException {
`getDistances` 나 `calculateDistances` 와 같이 더 좋은 메소드 이름 고민해주세요.

2020-04-05 05:00 UTC, wheejuni commented on BE/src/main/java/com/codesquad/dust6/utils/KakaoUtils.java
> +    public static final String KAKAO_API_KEY = "KakaoAK aceaab76688b123a34bf297440203425";
이런 key는 properties로 관리해주세요.

2020-04-06 01:18 UTC, crongro approved these changes
FE 아주 잘 구현하셨네요.!

2020-04-06 01:18 UTC, crongro commented on FE/package.json
> +		"dev:assets": "webpack --config ./config/webpack.config.dev -w",
다양한스크립트 좋네요.
dev와 production을 구분한 것이 매우 좋고요.
앞으로 이렇게 하시면 될 듯.

2020-04-06 01:18 UTC, crongro commented on FE/src/js/controllers/SwipeController.js
> +	if (e.target.dataset.swipeIgnore === "true") return;
문자열 true 는 별로 좋지 않네요. boolean타입과 헷갈리기도 하고요.
boolean 타입을 사용하시는 것이 좋겠죠

2020-04-06 01:18 UTC, crongro commented on FE/src/js/controllers/SwipeController.js
> +let xDiff = null;
변수이름을 좀더 구체적으로 하면 더 좋겠어요. 뭔지 이름만 보면 잘 모르겠어요.

2020-04-06 01:18 UTC, crongro commented on FE/src/js/controllers/SwipeController.js
> +document.addEventListener("touchstart", handleTouchStart, false);
calllback  함수 분리하니 좋네요.

2020-04-06 01:18 UTC, crongro commented on FE/src/js/controllers/SwipeController.js
> +			? (e.target.closest(".container").style.left = "-100vw")
가끔 보이는 이런 숫자들(-100)도 다 변수로 이름을 지정하는 습관을 가지시길!

2020-04-06 01:18 UTC, crongro commented on FE/src/js/main.js
> +const dustModel = new DustModel();
main.js 가 아주  깔끔하고 전체 코드의 초기화 과정을 볼 수 있어서 좋네요. 👍

2020-04-06 01:18 UTC, crongro commented on FE/src/js/models/DustModel.js
> +		const url = `${API.PROD.CURRENT_24HOURS}longitude=${DEFAULT_LOCATION.LONGITUDE}&latitude=${DEFAULT_LOCATION.LATITUDE}`;
URL 분리 잘했어요.

2020-04-06 01:18 UTC, crongro commented on FE/src/js/models/ForecastModel.js
> +		this.http = new Http();
http 는 뭔지 알겠는데요. 조금더 다른이름은 없을까? 너무 일반적인 이름이라서..

2020-04-06 01:18 UTC, crongro commented on FE/src/js/utils/Observable.js
> +			fetchData: new Set(),
set자료구조와 array 차이, 
map과 object의 차이를 공부하시면 좋아요.
알고쓰면 더 좋겠죠.

2020-04-06 01:32 UTC, reesekimm commented on FE/src/js/models/ForecastModel.js
> +		this.http = new Http();
넹 좀 더 구체적으로 네이밍 해볼게요!

2020-05-06 08:24 UTC, merged